### ISSUE TITLE
Readme markdown

### ISSUE THREAD

**Issue by stijnherfst** [avaxman/INFOMGP-Practical2#1]
Please fix the readme markdown

**Comment by avaxman** [comment]
What exactly is wrong with it?

**Comment by stijnherfst** [comment]
How it currently looks
![image](https://user-images.githubusercontent.com/8471644/54139401-c4549d80-4421-11e9-8255-7db3b84b5490.png)  

Versus how I suppose its meant to look like  

![image](https://user-images.githubusercontent.com/8471644/54139433-d46c7d00-4421-11e9-8c41-e40adbbaa17a.png)  

It's not a big problem, but does improve readability quite a bit. 
Changing 
> ##Handout date: 6/Mar/2019.  

Including a space after the pound sign will produce a title.

 ## Handout date: 6/Mar/2019.

**Comment by avaxman** [comment]
Ok, fixed. Thanks! I should note that not all MD readers are sensitive to that (and anyhow one is needed for the math).
